name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

        # All supported Perl versions except latest.
        perl: [
          '5.10', '5.12', '5.14', '5.16', '5.18',
          '5.20', '5.22', '5.24', '5.26', '5.28',
          '5.30', '5.32'
        ]

        # Variants of the latest Perl.
        include:
          - os: macos-latest
            perl: '5.34'

          - os: windows-latest
            perl: '5.34'

          - name: ' (dpss)'
            os: ubuntu-latest
            perl: '5.34'
            dpss: true

          - name: ' (kaiser)'
            os: ubuntu-latest
            perl: '5.34'
            kaiser: true

          - name: ' (plot)'
            os: ubuntu-latest
            perl: '5.34'
            plot: true

          # This is effectively our normal one: all features and cover.
          - name: ' (all)'
            os: ubuntu-latest
            perl: '5.34'
            cover: true
            dpss: true
            kaiser: true
            plot: true

    runs-on: ${{ matrix.os }}

    name: v${{ matrix.perl }} on ${{ matrix.os }}${{ matrix.name }}

    steps:
      - uses: actions/checkout@v2

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl -v

      - run: cpanm --installdeps -n .

      - if: ${{ matrix.cover }}
        run: cpanm -n Devel::Cover::Report::Coveralls

      - if: ${{ matrix.dpss }}
        run: cpanm -n PDL::LinearAlgebra::Special

      - if: ${{ matrix.kaiser }}
        run: cpanm -n PDL::GSLSF::BESSEL

      - if: ${{ matrix.plot }}
        uses: PDLPorters/devops/github-actions/install-dep-gnuplot@master

      - if: ${{ matrix.plot }}
        run: cpanm -n PDL::Graphics::Gnuplot

      - run: perl Makefile.PL

      - if: ${{ !matrix.cover }}
        run: make test

      - if: ${{ matrix.cover }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cover -report Coveralls -test
